/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ThemHangVeController;
import ControllerImpl.ThemHangVeControllerImpl;
import Model.Chuyenbay;
import Model.GiaHangVe;
import Model.HangVe;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author PRINCE D. TOAD
 */
public class CapnhatHangVeFrm extends javax.swing.JFrame {

    private ThemHangVeController ctrl;

    /**
     * Creates new form CapnhatHangVeFrm
     */
    public CapnhatHangVeFrm() {
        initComponents();

        ctrl = new ThemHangVeControllerImpl();
        loadListChuyenbay();
    }

    private void loadListChuyenbay() {
        List<Chuyenbay> listCB = ctrl.getListChuyenbay();

        for (Chuyenbay cb : listCB) {
            cbChuyenbay.addItem(cb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaVeThuonggia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoVeThuonggia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiaVeBinhdan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSoVeBinhdan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGiaVeTietkiem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoVeTietkiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtGiaVeSieuTietkiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSoVeSieuTietkiem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbChuyenbay = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thêm giá và số lượng hạng vé");

        jLabel2.setText("Hạng vé thương gia :");

        jLabel3.setText("Giá vé :");

        jLabel4.setText("Số lượng vé : ");

        jLabel5.setText("Giá vé :");

        jLabel6.setText("Số lượng vé : ");

        jLabel7.setText("Hạng vé bình dân :");

        jLabel8.setText("Giá vé :");

        jLabel9.setText("Số lượng vé : ");

        jLabel10.setText("Hạng vé bình dân tiết kiệm :");

        jLabel11.setText("Giá vé :");

        jLabel12.setText("Số lượng vé : ");

        jLabel13.setText("Hạng vé siêu tiết kiệm :");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Chọn mã chuyến bay :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(151, 151, 151)
                                            .addComponent(jLabel13))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(txtGiaVeSieuTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(46, 46, 46)
                                                    .addComponent(jLabel12)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtSoVeSieuTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(66, 66, 66)
                                                    .addComponent(jButton2)))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtGiaVeTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSoVeTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(151, 151, 151)
                                            .addComponent(jLabel10))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtGiaVeBinhdan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSoVeBinhdan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtGiaVeThuonggia, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSoVeThuonggia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addComponent(jLabel2)))
                            .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbChuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addGap(171, 171, 171)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(260, 260, 260))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbChuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiaVeThuonggia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoVeThuonggia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaVeBinhdan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoVeBinhdan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGiaVeTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoVeTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGiaVeSieuTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSoVeSieuTietkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String err = "";
        if (txtGiaVeThuonggia.getText().equals("")) {
            err += "Chưa nhập giá vé thương gia\n";
        }
        if (txtGiaVeBinhdan.getText().equals("")) {
            err += "Chưa nhập giá vé bình dân\n";
        }
        if (txtGiaVeTietkiem.getText().equals("")) {
            err += "Chưa nhập giá vé bình dân tiết kiệm\n";
        }
        if (txtGiaVeSieuTietkiem.getText().equals("")) {
            err += "Chưa nhập giá vé siêu tiết kiệm\n";
        }
        if (txtSoVeThuonggia.getText().equals("")) {
            err += "Chưa nhập số vé thương gia\n";
        }
        if (txtSoVeBinhdan.getText().equals("")) {
            err += "Chưa nhập số vé bình dân\n";
        }
        if (txtSoVeTietkiem.getText().equals("")) {
            err += "Chưa nhập số vé bình dân tiết kiệm\n";
        }
        if (txtSoVeSieuTietkiem.getText().equals("")) {
            err += "Chưa nhập số vé siêu tiết kiệm\n";
        }

        if (err.equals("")) {
            Chuyenbay cb = (Chuyenbay) cbChuyenbay.getSelectedItem();

            if (ctrl.kiemtraMaChuyenbay(cb.getMaChuyenbay())) {
                JOptionPane.showMessageDialog(null, "Mã chuyến bay đã tồn tại",
                        "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                GiaHangVe giaHVThuonggia = new GiaHangVe();
                GiaHangVe giaHVBinhdan = new GiaHangVe();
                GiaHangVe giaHVTietkiem = new GiaHangVe();
                GiaHangVe giaHVSieuTietkiem = new GiaHangVe();
                
                try {
                    giaHVThuonggia.setGiaHangVe(Integer.parseInt(txtGiaVeThuonggia.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số giá vé thương gia\n";
                }
                
                try {
                    giaHVBinhdan.setGiaHangVe(Integer.parseInt(txtGiaVeBinhdan.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số giá vé bình dân\n";
                }
                
                try {
                    giaHVTietkiem.setGiaHangVe(Integer.parseInt(txtGiaVeTietkiem.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số giá vé bình dân tiết kiệm\n";
                }
                
                try {
                    giaHVSieuTietkiem.setGiaHangVe(Integer.parseInt(txtGiaVeSieuTietkiem.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số giá vé siêu tiết kiệm\n";
                }
                
                try {
                    giaHVThuonggia.setSoluong(Integer.parseInt(txtSoVeThuonggia.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số lượng giá vé thương gia\n";
                }
                
                try {
                    giaHVBinhdan.setSoluong(Integer.parseInt(txtSoVeBinhdan.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số lượng giá vé bình dân\n";
                }
                
                try {
                    giaHVTietkiem.setSoluong(Integer.parseInt(txtSoVeTietkiem.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số lượng giá vé tiết kiệm\n";
                }
                
                try {
                    giaHVSieuTietkiem.setSoluong(Integer.parseInt(txtSoVeSieuTietkiem.getText()));
                } catch (NumberFormatException e) {
                    err += "Nhập chưa đúng định dạng số lượng giá vé siêu tiết kiệm\n";
                }
                
                if(err.equals("")){
                    giaHVThuonggia.setChuyenBay(cb);
                    HangVe hvThuonggia = new HangVe();
                    hvThuonggia.setMaHangVe(1);
                    giaHVThuonggia.setHangVe(hvThuonggia);
                    ctrl.themGiaHangVe(giaHVThuonggia);
                    
                    giaHVBinhdan.setChuyenBay(cb);
                    HangVe hvBinhdan = new HangVe();
                    hvBinhdan.setMaHangVe(2);
                    giaHVBinhdan.setHangVe(hvBinhdan);
                    ctrl.themGiaHangVe(giaHVBinhdan);
                    
                    giaHVTietkiem.setChuyenBay(cb);
                    HangVe hvTietkiem = new HangVe();
                    hvTietkiem.setMaHangVe(3);
                    giaHVTietkiem.setHangVe(hvTietkiem);
                    ctrl.themGiaHangVe(giaHVTietkiem);
                    
                    giaHVSieuTietkiem.setChuyenBay(cb);
                    HangVe hvSieuTietkiem = new HangVe();
                    hvSieuTietkiem.setMaHangVe(4);
                    giaHVSieuTietkiem.setHangVe(hvSieuTietkiem);
                    ctrl.themGiaHangVe(giaHVSieuTietkiem);
                    
                    JOptionPane.showMessageDialog(null, "Thêm các hạng vé thành công",
                    "Thông báo", JOptionPane.OK_OPTION);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, err,
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, err,
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapnhatHangVeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapnhatHangVeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapnhatHangVeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapnhatHangVeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapnhatHangVeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbChuyenbay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGiaVeBinhdan;
    private javax.swing.JTextField txtGiaVeSieuTietkiem;
    private javax.swing.JTextField txtGiaVeThuonggia;
    private javax.swing.JTextField txtGiaVeTietkiem;
    private javax.swing.JTextField txtSoVeBinhdan;
    private javax.swing.JTextField txtSoVeSieuTietkiem;
    private javax.swing.JTextField txtSoVeThuonggia;
    private javax.swing.JTextField txtSoVeTietkiem;
    // End of variables declaration//GEN-END:variables
}
