/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author PRINCE D. TOAD
 */
public class ManhinhQuanlyFrm extends javax.swing.JFrame {

    /**
     * Creates new form ManhinhQuanly
     */
    public ManhinhQuanlyFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLenlichBay = new javax.swing.JButton();
        btnQlThongtinSanbay = new javax.swing.JButton();
        btnTKKhachTheoGio = new javax.swing.JButton();
        btnTKChangbayTheoDoanhThu = new javax.swing.JButton();
        btnChangbay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Đăng nhập chức năng quản lý");

        btnLenlichBay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLenlichBay.setText("Lên lịch bay cho chuyến bay");
        btnLenlichBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenlichBayActionPerformed(evt);
            }
        });

        btnQlThongtinSanbay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQlThongtinSanbay.setText("Quản lý thông tin một sân bay");

        btnTKKhachTheoGio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTKKhachTheoGio.setText("Thống kê lượng khách theo khung giờ");

        btnTKChangbayTheoDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTKChangbayTheoDoanhThu.setText("Thống kê các chặng bay theo doanh thu");

        btnChangbay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChangbay.setText("Quản lý chặng bay");
        btnChangbay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangbayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLenlichBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQlThongtinSanbay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTKKhachTheoGio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTKChangbayTheoDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangbay, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnQlThongtinSanbay)
                .addGap(30, 30, 30)
                .addComponent(btnChangbay)
                .addGap(27, 27, 27)
                .addComponent(btnLenlichBay)
                .addGap(27, 27, 27)
                .addComponent(btnTKKhachTheoGio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnTKChangbayTheoDoanhThu)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangbayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangbayActionPerformed
        // TODO add your handling code here:
        ThemChangbayFrm changbayFrm = new ThemChangbayFrm();
        changbayFrm.setVisible(true);
    }//GEN-LAST:event_btnChangbayActionPerformed

    private void btnLenlichBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenlichBayActionPerformed
        // TODO add your handling code here:
        LenLichBayFrm bayFrm = new LenLichBayFrm();
        bayFrm.setVisible(true);
    }//GEN-LAST:event_btnLenlichBayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManhinhQuanlyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManhinhQuanlyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManhinhQuanlyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManhinhQuanlyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManhinhQuanlyFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangbay;
    private javax.swing.JButton btnLenlichBay;
    private javax.swing.JButton btnQlThongtinSanbay;
    private javax.swing.JButton btnTKChangbayTheoDoanhThu;
    private javax.swing.JButton btnTKKhachTheoGio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
